version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pgbot-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pgbot
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    restart: always
